sonar.projectKey=aceest-fitness-devops
sonar.projectName=ACEest Fitness & Gym DevOps
sonar.projectVersion=3.2.4

sonar.sources=app
sonar.tests=tests

sonar.language=py
sonar.sourceEncoding=UTF-8

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=pytest-report.xml
sonar.python.version=3.12

sonar.exclusions=versions/**,.venv/**,**/__pycache__/**,htmlcov/**,build/**,dist/**

# Suppress specific false-positives
# S104: 0.0.0.0 bind is intentional for containerized deployment (gunicorn is the prod entrypoint)
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=python:S104
sonar.issue.ignore.multicriteria.e1.resourceKey=app/main.py

sonar.scm.provider=git
