apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-fitness-green
  labels:
    app: aceest-fitness
    color: green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aceest-fitness
      color: green
  template:
    metadata:
      labels:
        app: aceest-fitness
        color: green
    spec:
      containers:
        - name: aceest-fitness
          image: dshekhawat06640/aceest-fitness:3.2.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet: { path: /health, port: 5000 }
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            requests: { cpu: "50m", memory: "96Mi" }
            limits:   { cpu: "250m", memory: "256Mi" }
