apiVersion: v1
kind: Service
metadata:
  name: aceest-fitness-a
  labels:
    app: aceest-fitness
    variant: a
spec:
  type: NodePort
  selector:
    app: aceest-fitness
    variant: a
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30083
